<?php
/** @var \Typesetsh\Pdf\Block\Items\Invoice $block */
$invoice = $block->getInvoice();
?>
<div class="table-wrapper table-order-items invoice">
    <table class="table-order-items invoice">
        <thead>
            <tr>
                <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                <th class="col price"><?= $block->escapeHtml(__('Price')) ?></th>
                <th class="col qty"><?= $block->escapeHtml(__('Qty Invoiced')) ?></th>
                <th class="col subtotal"><?= $block->escapeHtml(__('Subtotal')) ?></th>
            </tr>
        </thead>
        <?php $_items = $invoice->getItemsCollection() ?>
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif ?>
        <?php endforeach ?>
        <tfoot>
            <?= $block->getInvoiceTotalsHtml($invoice) ?>
        </tfoot>
    </table>
</div>
