<?php
/** @var \Typesetsh\Pdf\Block\Creditmemo $block */

$creditmemo = $block->getCreditmemo();
$order = $creditmemo->getOrder();
?>


<h1><?= $block->escapeHtml(__('Credit Memo')) ?> #<?= $block->escapeHtml($creditmemo->getIncrementId()) ?></h1>
<p><?= $block->escapeHtml(__('Date')) ?>: <?= $block->formatDate($creditmemo->getCreatedAt(), IntlDateFormatter::LONG) ?></p>


<section class="order-information">
    <div class="payment">
        <h3><?= $block->escapeHtml(__('Payment Method')) ?></h3>
        <?= $block->getInfoBlockHtml() ?>
    </div>

    <?php if (!$order->getIsVirtual()) : ?>
        <div class="shipping-address">
            <h3><?= $block->escapeHtml(__('Shipping Address')) ?></h3>

            <?php $shipping = $creditmemo->getShippingAddress() ?>
            <address><?= /* @noEscape */ $block->formatAddress($shipping, 'html') ?></address>
        </div>
        <div class="shipping">
            <h3><?= $block->escapeHtml(__('Shipping Method')) ?></h3>
            <?= $block->escapeHtml($creditmemo->getOrder()->getShippingDescription()) ?>
        </div>
    <?php endif ?>

</section>

<?= $block->getChildHtml('items') ?>
